export { default as IconArrowBackUp } from '@tabler/icons-react/dist/esm/icons/IconArrowBackUp.mjs';
export { default as IconArrowForwardUp } from '@tabler/icons-react/dist/esm/icons/IconArrowForwardUp.mjs';
export { default as IconArticle } from '@tabler/icons-react/dist/esm/icons/IconArticle.mjs';
export { default as IconDeviceFloppy } from '@tabler/icons-react/dist/esm/icons/IconDeviceFloppy.mjs';
export { default as IconFilePencil } from '@tabler/icons-react/dist/esm/icons/IconFilePencil.mjs';
export { default as IconFolderOpen } from '@tabler/icons-react/dist/esm/icons/IconFolderOpen.mjs';
export { default as IconRowInsertBottom } from '@tabler/icons-react/dist/esm/icons/IconRowInsertBottom.mjs';
export { default as IconTool } from '@tabler/icons-react/dist/esm/icons/IconTool.mjs';
export { default as IconTrashX } from '@tabler/icons-react/dist/esm/icons/IconTrashX.mjs';
